version: "3.8"
services:
  db:
    image: mysql
    container_name: blogapi-db
    restart: always
    environment:
      MYSQL_USER: "root"
      MYSQL_DATABASE: "blogapi"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d/0_init.sql
    tty: true
    networks:
      - blogapi-network
  application:
    container_name: blogapi-application
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - blogapi-network
    depends_on:
      - "db"
volumes:
  db-data:
networks:
  blogapi-network:
    name: blogapi-network
    driver: bridge
